name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script
      run: python update_readme.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit changes
      run: |
        git add README.md
        git commit -m 'Update README with current date'
      continue-on-error: true

    - name: Pull and push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git remote set-url origin https://github-actions:${{ secrets.PAT }}@github.com/Luna5akura/Luna5akura.git
        git pull origin main --rebase
        git push origin HEAD:main
